name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      # si un intérprete falla, los demás siguen (mejor feedback)
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      # 1) checkout
      - uses: actions/checkout@v4

      # 2) seleccionar Python y activar la caché de pip
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      # 3) instalar dependencias
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # si usas requirements.txt
          pip install -r requirements.txt
          # para extras de desarrollo (pytest, black, etc.)
          pip install -r requirements-dev.txt
          # instalar el propio paquete en modo editable
          pip install -e .

      # 4) lanzar los tests
      - name: Run tests
        run: |
          pytest -q
